fix: github.event.repository prop doesn't exist
https://github.com/davorpa/testing-github-actions/runs/3436979434?check_suite_focus=true#step:2:1

Error: .github/workflows/print-events-repo-name.yml (Line: 51, Col: 32): A mapping was not expected